# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: devel
dist: trusty
sudo: required
cache: packages
after_success:
  - Rscript -e 'covr::codecov(type = "all")'


## for sf
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
